# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: m133225's journey in HubTurbo
email: a0132760@u.nus.edu
description: > # this means to ignore newlines until "baseurl:"
  CS3281 Blog for HubTurbo
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: m133225 
github_username:  m133225

# Build settings
markdown: kramdown
